### ISSUE TITLE
[1.11.2]Server crashed when some in the nether

### ISSUE THREAD

**Issue by Amamiya-Nagisa** [rubensworks/EvilCraft#511] opened 2017-01-18 02:29 UTC
Forge log link:http://pastebin.com/WETe9p5W

Crash-report:http://pastebin.com/YKdEv9TF

Problem:Server crashed when some in the nether

Steps to reproduce the problem:
-Go to the nether

**Comment by rubensworks** [comment] 2017-01-18 07:09
Duplicate of #510.

@Amamiya-Nagisa Please always check the closed issues before reporting a new one.

**Closed as completed by rubensworks** 2017-01-18 07:09 UTC
Labels: duplicate
