### ISSUE TITLE
Null pointer crash

### ISSUE THREAD

**Issue by Austin5003** [rubensworks/EvilCraft#764] opened 2019-03-20 02:19 UTC
#### Issue type:
Crash during initialization
- :bug: Bug

____

#### Short description:

Initialization crash when using cyclops core version 1.1.0

#### Steps to reproduce the problem:

1. Start the game

____

#### Versions:

- This mod: 10.70
- Minecraft: 1.12.2
- Forge: 14.23.5.2814

#### Log file:

https://pastebin.com/fMKcSb9Y

**Comment by rubensworks** [comment] 2019-03-20 07:08
Duplicate of https://github.com/CyclopsMC/CyclopsCore/issues/134

**Closed as completed by rubensworks** 2019-03-20 07:08 UTC
Labels: duplicate
