### ISSUE TITLE
Null registered as an EntityRender

### ISSUE THREAD

**Issue by BluSunrize** [rubensworks/EvilCraft#468] opened 2016-08-23 06:49 UTC
Issue Link:
https://github.com/BluSunrize/ImmersiveEngineering/issues/1298

Problem:
There seem to have an incompatibility issue between EvilCraft and Immersive Engineering
It's an NPE at me iterating through "Minecraft.getMinecraft().getRenderManager().entityRenderMap", meaning that somehow a null value found its way in there. Reporters on my tracker have narrowed it down to EvilCraft, which leads me to assume that you register null for an EntityRenderer at some point. Despite the fact that I can nullcheck this, you should probs look into that on your side as well, since it's bad practice ^^

Expected behaviour:
...not crashing?

Steps to reproduce the problem:
Install IE and Evilcraft

**Comment by rubensworks** [comment] 2016-08-23 06:53
You're right, that null renderer should not be there, will look into it later today.
Duplicate of #467

**Comment by BluSunrize** [comment] 2016-08-23 07:02
Great, thanks ^^

**Comment by rubensworks** [comment] 2016-08-23 16:46
Fixed in 604d40bb6940a9b33ad7f268346a2dfa12046952, will be released as part of EvilCraft 0.10.9 shortly.

**Closed as completed by rubensworks** 2016-08-23 16:46 UTC
