### ISSUE TITLE
java.lang.IllegalStateException: Pose stack not empty when using spectral glasses

### ISSUE THREAD

**Issue by nmills3** [rubensworks/EvilCraft#878] opened 2021-06-21 20:40 UTC
#### Issue type:

- :bug: Game Crashed

____

#### Short description:

When using the spectral glasses in my modpack i seem to occasionally get a java.lang.IllegalStateException: Pose stack not empty error and the game crashes. this issue seems to happen mostly at night so may be related to a specific mob. Once the glasses have been taken off the issue seems to stop but this isn't a great solution

#### Steps to reproduce the problem:

1. Unknown

#### Expected behaviour:

For the game not to crash

____

#### Versions:

- This mod: 1.1.6
- Minecraft: 1.16.5
- Forge: 36.1.16

#### Log file:

https://pastebin.com/psGYTgKc

**Comment by rubensworks** [comment] 2021-06-22 07:18
Duplicate of #858. Please follow up here: Mithion/Mana-And-Artifice#190

**Closed as completed by rubensworks** 2021-06-22 07:18 UTC
Labels: other mod, mc-1.16
