### ISSUE TITLE
Evilcraft rendering crash

### ISSUE THREAD

**Issue by Sunconure11** [rubensworks/EvilCraft#747] opened 2019-01-16 13:37 UTC
https://github.com/CyclopsMC/CyclopsCore/issues/126

**Comment by rubensworks** [comment] 2019-01-17 06:43
Duplicate of #748

**Comment by Sunconure11** [comment] 2019-01-19 19:13
https://paste.dimdev.org/ewokaboven.mccrash

<blockquote><div><strong><a href="https://paste.dimdev.org/ewokaboven.mccrash">hastebin</a></strong></div></blockquote>

**Comment by Sunconure11** [comment] 2019-01-23 05:29
https://paste.dimdev.org/wowafovihi.mccrash

<blockquote><div><strong><a href="https://paste.dimdev.org/wowafovihi.mccrash">hastebin</a></strong></div></blockquote>

**Comment by Sunconure11** [comment] 2019-01-24 23:12
https://paste.dimdev.org/jucojinera.mccrash

It's related to Connected Textures Mod, a requirement of Chisel. @rubensworks 

<blockquote><div><strong><a href="https://paste.dimdev.org/jucojinera.mccrash">hastebin</a></strong></div></blockquote>

**Comment by rubensworks** [comment] 2019-01-25 07:28
@Sunconure11 It now looks like an issue with CTM then. Our models work fine without CTM loaded, so it looks like they are doing some funky things with them. Please report it at CTM's issue tracker.

**Comment by tterrag1098** [comment] 2019-01-26 02:12
`null` is not a valid return from getQuads. This should be an empty list: 

https://github.com/CyclopsMC/EvilCraft/blob/master-1.12/src/main/java/org/cyclops/evilcraft/core/client/model/BroomPartModelBaked.java#L38

**Comment by rubensworks** [comment] 2019-01-26 07:27
It's been a while since I wrote that code, but the zero-args constructor should only act as a factory for new baked models that are created when calling `handleItemState`.

@tterrag1098 Is CTM changing things so that this method is not being called anymore? Because this would likely break most of my dynamic models.

**Comment by tterrag1098** [comment] 2019-01-26 08:31
handleItemState is your own method...I don't influence when it's called.

**Comment by rubensworks** [comment] 2019-01-26 08:47
> handleItemState is your own method...I don't influence when it's called.

>> It's been a while since I wrote that code

I guess it's about time I delve into this the codebase again.

**Comment by rubensworks** [comment] 2019-01-27 14:03
Ok, the bug was indeed fully caused by something on my end.
I should have looked at this one in more detail from the start.

**Closed as completed** 2019-01-27 14:04 UTC
Labels: bug, duplicate
