### ISSUE TITLE
broom part recipes all make the same item

### ISSUE THREAD

**Issue by ApostolosRisen** [rubensworks/EvilCraft#782] opened 2019-07-28 14:32 UTC
The title covers the issue pretty well, I will be testing things later to see if I can find a specific mod to cause this I havent found it yet 140+ mods to check, attached are two photos showing the broom basics pages that show the recipes for broom parts, short of crafttweaker I dont know what could be causing this issue.

minecraft version: 1.12.2
forge version: 14.23.5.2768
evilcraft version: 1.12.2-0.10.72 ( will be updating to newest to see if I run into the same issue)

modpack link: https://www.technicpack.net/modpack/lampcats-playground.1402224
on the off chance you look and see a mod that you know has compatibility issues

![broom page two and three](https://user-images.githubusercontent.com/26664327/62007941-a910d300-b121-11e9-9e88-af41d71bb81e.PNG)
![page one brooms](https://user-images.githubusercontent.com/26664327/62007942-a910d300-b121-11e9-83dc-8d5384ac6da2.PNG)

**Comment by rubensworks** [comment] 2019-07-29 06:26
That definitely looks like a problem with some mod messing with recipes.
Crafttweaker is also the only one that I can think of that can cause this, but I'm not sure.

**Comment by ApostolosRisen** [comment] 2019-07-29 17:37
So checking and we aren’t using craftyweaker for anything, that being said it probably is one of the other mods doing this and short of checking all of them one by one I have no idea which one it is I’ll try and get my team to check it with me

**Comment by rubensworks** [comment] 2019-07-29 17:38
Thanks! Be sure to let me know the outcome.

**Comment by ApostolosRisen** [comment] 2019-07-29 20:17
so after uhhh almost four hours I found it, its foamfix from asiekierka, newest version of both mods produces the same issue

**Comment by rubensworks** [comment] 2019-07-30 06:13
That's interesting...
So foamfix must be modifying recipes somehow.

**Comment by ApostolosRisen** [comment] 2019-07-30 13:13
as far as I know that isnt what it is supposed to do but im not much of a coder so I cant say much past that

**Comment by asiekierka** [comment] 2019-10-07 07:21
Should be fixed in FoamFix 0.10.6.

**Comment by rubensworks** [comment] 2019-10-07 09:39
That's great, thanks @asiekierka!

**Comment by asiekierka** [comment] 2019-10-07 18:13
Ah, dang, no, don't close it yet. (Or do, if it works fine now - see below.) Apparently the feature I removed which might have been impactful was actually commented out elsewhere all along.

I could not, however, reproduce the issue on 0.10.7, so there's that. Could be just visual, too - I mess with item models substantially.

**Comment by rubensworks** [comment] 2019-11-23 11:17
@ApostolosRisen Could you confirm whether or not this issue still persists for you?

**Comment by ApostolosRisen** [comment] 2019-11-23 16:51
So with my last check there was not a version of foamfix out aside from the one I am using that worked with the version of forge that is currently run on my server, as 0.10.6 that was mentioned above is not available on curseforge for me to try at this time, I could however set up a new modpack with just those two mods and test it that way for you guys

**Comment by asiekierka** [comment] 2019-11-23 19:52
0.10.6 was broken, which is why it was pulled.

**Comment by rubensworks** [comment] 2020-08-15 14:46
Closing this due to inactivity, feel free to re-open should this still occur.

**Closed as completed by rubensworks** 2020-08-15 14:46 UTC
Labels: bug, other mod

**Comment by Steelfire789** [comment] 2022-02-22 01:21
Hi, I've encountered this same issue again in my mod pack. Evilcraft and Foam Fix seem to get along fine together on their own, however this issue occurs again with the addition of ExtraCells2.

Forge: 1.12.2 - 14.23.5.2860
Evilcraft: 1.12.2 - 0.10.78
Foam: 1.12.2 - 0.10.14
ExtraCells2: 1.12.2 - 2.6.7

I assume this happens because ExtraCells2 handles their fluid patterns and a few other items the same way as broom parts (same item ID with different NBT tags
![OoD Recipies](https://user-images.githubusercontent.com/70979654/155045981-238dcebf-e0fc-49bf-b304-36b4d6a05a6e.jpg)
![Creative Tab](https://user-images.githubusercontent.com/70979654/155045991-61aea665-9a2f-4cc0-8b4c-47b385a13dfb.jpg)
)
