### ISSUE TITLE
Crash placing Dark Tank

### ISSUE THREAD

**Issue by Grunash** [rubensworks/EvilCraft#371] opened 2016-05-11 21:02 UTC
The server throw this error before close itself:

[22:53:48] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:711) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386) ~[la.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=draining, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192) ~[ard$a.class:?]
    at org.cyclops.evilcraft.tileentity.TileDarkTank.shouldAutoDrain(TileDarkTank.java:70) ~[TileDarkTank.class:?]
    at org.cyclops.evilcraft.tileentity.TileDarkTank.updateTileEntity(TileDarkTank.java:75) ~[TileDarkTank.class:?]
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.updateTicking(CyclopsTileEntity.java:95) ~[CyclopsTileEntity.class:?]
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.access$000(CyclopsTileEntity.java:38) ~[CyclopsTileEntity.class:?]
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity$TickingTileComponent.func_73660_a(CyclopsTileEntity.java:323) ~[CyclopsTileEntity$TickingTileComponent.class:?]
    at org.cyclops.evilcraft.tileentity.TileDarkTank.func_73660_a(TileDarkTank.java:40) ~[TileDarkTank.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1791) ~[aht.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[lp.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705) ~[MinecraftServer.class:?]
    ... 4 more

This is the error log:

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 11/05/16 22:53
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=draining, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
    at org.cyclops.evilcraft.tileentity.TileDarkTank.shouldAutoDrain(TileDarkTank.java:70)
    at org.cyclops.evilcraft.tileentity.TileDarkTank.updateTileEntity(TileDarkTank.java:75)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.updateTicking(CyclopsTileEntity.java:95)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.access$000(CyclopsTileEntity.java:38)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity$TickingTileComponent.func_73660_a(CyclopsTileEntity.java:323)
    at org.cyclops.evilcraft.tileentity.TileDarkTank.func_73660_a(TileDarkTank.java:40)
    at net.minecraft.world.World.func_72939_s(World.java:1791)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
    at org.cyclops.evilcraft.tileentity.TileDarkTank.shouldAutoDrain(TileDarkTank.java:70)
    at org.cyclops.evilcraft.tileentity.TileDarkTank.updateTileEntity(TileDarkTank.java:75)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.updateTicking(CyclopsTileEntity.java:95)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity.access$000(CyclopsTileEntity.java:38)
    at org.cyclops.cyclopscore.tileentity.CyclopsTileEntity$TickingTileComponent.func_73660_a(CyclopsTileEntity.java:323)
    at org.cyclops.evilcraft.tileentity.TileDarkTank.func_73660_a(TileDarkTank.java:40)

-- Block entity being ticked --
Details:
    Name: darkTank // org.cyclops.evilcraft.tileentity.TileDarkTank
    Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-19,65,163), Chunk: (at 13,4,3 in -2,10; contains blocks -32,0,160 to -17,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1791)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
    Level name: world
    All players: 2 total; [EntityPlayerMP['Grunash'/459, l='world', x=-17,44, y=65,00, z=161,78], EntityPlayerMP['Metafungu'/9942, l='world', x=-19,24, y=65,00, z=164,65]]
    Chunk stats: ServerChunkCache: 600 Drop: 0
    Level seed: 11010010011021
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-156,64,236), Chunk: (at 4,4,12 in -10,14; contains blocks -160,0,224 to -145,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 500457 game time, 508474 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 5776 (now: false), thunder time: 46634 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1181368464 bytes (1126 MB) / 1424490496 bytes (1358 MB) up to 1895825408 bytes (1808 MB)
    JVM Flags: 2 total; -Xms1024M -Xms1024M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.23 Powered by Forge 12.16.1.1887 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1887-universal.jar) 
    UCHIJAAAA   Forge{12.16.1.1887} [Minecraft Forge](forge-1.9-12.16.1.1887-universal.jar) 
    UCHIJAAAA   animalbikes{1.8} [Animal Bikes](AnimalBikes_1.9.0%2826mar16%29.jar) 
    UCHIJAAAA   BiomesOPlenty{4.0.1.2006} [Biomes O' Plenty](BiomesOPlenty-1.9-4.0.1.2006-universal.jar) 
    UCHIJAAAA   cyclopscore{0.5.8} [Cyclops Core](CyclopsCore-1.9-0.5.8.jar) 
    UCHIJAAAA   evilcraft{0.9.9} [EvilCraft](EvilCraft-1.9-0.9.9.jar) 
    Loaded coremods (and transformers): 
    Profiler Position: N/A (disabled)
    Player Count: 2 / 20; [EntityPlayerMP['Grunash'/459, l='world', x=-17,44, y=65,00, z=161,78], EntityPlayerMP['Metafungu'/9942, l='world', x=-19,24, y=65,00, z=164,65]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by rubensworks** [comment] 2016-05-12 06:17
Duplicate of #368, please update to the latest EC version.

**Closed as completed by rubensworks** 2016-05-12 06:17 UTC
Labels: duplicate

**Comment by Grunash** [comment] 2016-05-12 19:25
Sorry for the loss of time, I though these were different problems.

**Comment by rubensworks** [comment] 2016-05-13 05:24
@Grunash No problem ;-) It's better to have duplicate issues, than unreported issues.
