### ISSUE TITLE
Chrash while initializing 

### ISSUE THREAD

**Issue by Rams59** [rubensworks/EvilCraft#765] opened 2019-03-20 18:45 UTC
#### Issue type: Minecraft shuts down while initzialising cause of an evilcraft issue

- :bug: Bug

____

#### Short description:

Minecraft shuts down while initzialising cause of an evilcraft issue

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 1.12.2-0.10.70
- Minecraft: 1.12
- Forge: 14.23.5.2821

#### Log file:

https://pastebin.com/YMTwy624

**Comment by rubensworks** [comment] 2019-03-20 18:46
Duplicate of https://github.com/CyclopsMC/CyclopsCore/issues/134

**Closed as completed by rubensworks** 2019-03-20 18:46 UTC
Labels: duplicate
