### ISSUE TITLE
aether legacy and ctm mod compatability

### ISSUE THREAD

**Issue by EternalOne11** [rubensworks/EvilCraft#784] opened 2019-08-03 01:25 UTC
- :bug: Bug:
just crashed as soon as I load a world.

- This mod: EvilCraft-1.12.2-0.10.77
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

https://paste.dimdev.org/orucumikum.mccrash

**Comment by rubensworks** [comment] 2019-08-03 06:41
Looks like a duplicate of #756, for which I'm awaiting @tterrag1098's help.

**Closed as completed by rubensworks** 2019-08-03 06:41 UTC
Labels: duplicate
