### ISSUE TITLE
Spirit Furnace Crash

### ISSUE THREAD

**Issue by TigersFangs** [rubensworks/EvilCraft#405] opened 2016-05-29 21:10 UTC
Forge log link: http://pastebin.com/EGMG7pUa  (Crash Log Error. Whole Forge Log too large for free users)
Log File: [latest.zip](https://github.com/CyclopsMC/EvilCraft/files/288550/latest.zip)

Problem: Crash on trying to use Spirit Furnace to summon a mob

Expected behaviour:  Intended operation of summoning the mob and providing the drops

Steps to reproduce the problem:  (In Creative, but should occur in survival as well I would imagine)
- Kill a mob
- Use a Vengeance Focus to capture the spirit with a Box of Eternal Closure
- Recover the now filled Box of Eternal Closure (Either by Creative "Pick Block" or Survival pickaxe)
- Build a Spirit Furnace of appropriate size
- Fill the furnace with 10 buckets of blood
- Place the Box of Eternal Closure with the spirit in it into the Spirit Furnace
- Wait for the progress bar to fill
- Complete game crash upon reaching 100% progress

**Comment by rubensworks** [comment] 2016-05-30 13:55
I think I already fixed this in the latest 1.9.4 version (I'll check later to make sure)
I won't be doing any new releases for 1.9 I'm afraid.

**Comment by immortaleeb** [comment] 2016-06-09 18:38
This seems to be fixed in 1.9.4 - I can't reproduce it and like mentioned above, there won't be any future updates for 1.9.x < 1.9.4

**Closed as completed by immortaleeb** 2016-06-09 18:38 UTC
Labels: unreproducible, mc-1.9
