### ISSUE TITLE
Blood Chest + Tinker Tools = ticking error

### ISSUE THREAD

**Issue by Bunnyboy40** [rubensworks/EvilCraft#593] opened 2017-09-21 09:39 UTC
----- REMOVE ME START -----
[crash-2017-09-21_19.27.05-server.txt](https://github.com/CyclopsMC/EvilCraft/files/1320660/crash-2017-09-21_19.27.05-server.txt)

----- REMOVE ME END -----
 
Forge log link: forge-1.10.2-12.18.3.2185-installer-win

Problem: TInkertool scythe in blood chest crashed game. (was only item in there) (was auto-resupplying blood chest using ender io fluid conduits)

Expected behaviour:
A tinker tool in evilcraft blood chest does something bad and the game kills itself (the scythe repairs fine, assuming that when it completes repairing the game crashes)
Steps to reproduce the problem:
-setup blood chest from evilcraft to be autosupplied with blood, place tinker scythe into chest until it repairs fully
-ticking error

**Comment by rubensworks** [comment] 2017-09-21 09:43
Seems to be a duplicate of #532.

So another mod is causing this, possibly a TCon addon.
Please report this issue to the addon's issue tracker.

**Closed as completed by rubensworks** 2017-09-21 09:43 UTC
Labels: duplicate
