### ISSUE TITLE
Crafttweaker no longer recognizes the machines after Update

### ISSUE THREAD

**Issue by Freebi85** [rubensworks/EvilCraft#766] opened 2019-03-22 09:00 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:
Hello =)
Crafttweaker no longer recognizes the machines after Update (Blood Infuser)
The error message "No such member" always appears and the custom recipes dosen't work anymore.

#### Steps to reproduce the problem:
1. Write any kinde of crafttweaker recipe for the blood-infuser

#### Versions:
- This mod: 1.12.2-0.10.71
- Minecraft: 1.12.2
- Forge: .2822

**Comment by rubensworks** [comment] 2019-03-22 12:46
It's possible that this is the same problem as https://github.com/CyclopsMC/IntegratedDynamics-Compat/issues/22

(Possible caused by the recent CurseForge upload issue, which required me to jump through some mod building hoops)

**Comment by rubensworks** [comment] 2019-03-24 07:51
Will be fixed in 0.10.72

**Closed as completed by rubensworks** 2019-03-24 07:51 UTC
Labels: bug
