### ISSUE TITLE
Expected signature is not found

### ISSUE THREAD

**Issue by Mesopolies** [rubensworks/EvilCraft#767] opened 2019-03-23 17:56 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

Here is the server log error, though evilcraft appears to run with no issue,
[10:22:49] [Server thread/ERROR] [FML]: The mod evilcraft is expecting signature bd0353b3e8a2810d60dd584e256e364bc3bedd44 for source EvilCraft-1.12.2-0.10.71.jar, however there is no signature matching that description

#### Steps to reproduce the problem:

1. Run evilcraft from sever
2. examine log

#### Expected behaviour:

No error messages in log
____

#### Versions:

- This mod: 1.12.2-0.10.71
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2810

**Comment by rubensworks** [comment] 2019-03-24 06:46
Possibly caused by the recent CurseForge upload issue, which required me to jump through some mod building hoops

**Comment by rubensworks** [comment] 2019-03-24 07:51
Will be fixed in 0.10.72

**Closed as completed by rubensworks** 2019-03-24 07:51 UTC
Labels: bug
