### ISSUE TITLE
Smashing Broom with Pedstal instantly crash server

### ISSUE THREAD

**Issue by AntonioKeyxer** [rubensworks/EvilCraft#1057] opened 2024-09-05 15:03 UTC
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Fly in a Broom with the Smash Property and break Evilcraft Pedestal

#### Expected behaviour: Just Break the Pedestal not crash

____

#### Versions: 1.2.45

- This mod: 1.2.45
- Minecraft: 1.20.1
- Mod loader version: 

#### Log file: 
Details:
	Entity Type: evilcraft:broom (org.cyclops.evilcraft.entity.item.EntityBroom)
	Entity ID: 1022507
	Entity Name: entity.evilcraft.broom
	Entity's Exact location: 135.30, 6.38, -549.30
	Entity's Block location: World: (135,6,-550), Section: (at 7,6,10 in 8,0,-35; chunk contains blocks 128,-64,-560 to 143,319,-545), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,-64,-1024 to 511,319,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [ServerPlayer['sould'/898930, l='ServerLevel[world]', x=135.30, y=6.38, z=-549.30](sould at 135.30000001192093,6.376938961118683,-549.3000000119209)]
	Entity's Vehicle: null

**Comment by rubensworks** [comment] 2024-09-05 15:04
Thanks for reporting!

**Comment by AntonioKeyxer** [comment] 2024-09-05 16:44
It also happens when the broom collides with the blood chest.

**Comment by rubensworks** [comment] 2024-09-05 17:02
This should be fixed in the latest release, as it's probably caused by the same root problem as your other issue: #1056.

Please let me know if this would still occur with the latest release.

**Closed as completed by rubensworks** 2024-09-05 17:02 UTC
Labels: bug, mc-1.20
