### ISSUE TITLE
Can't extract from Spirit Furnace with XNet

### ISSUE THREAD

**Issue by matthewspeck** [rubensworks/EvilCraft#686] opened 2018-05-02 17:02 UTC
#### Issue type:
- :bug: Bug

#### Short description:
XNet is not extracting mob drops from the Spirit Furnace and inserting into a chest.

[XNet issue thread](https://github.com/McJty/XNet/issues/264)

#### Expected behaviour:
With an XNet network connecting a Spirit Furnace to a Diamond Chest, with an item channel extracting items from the Spirit Furnace and inserting into the Diamond Chest, the mob drops from the tortured Vengeance Spirit should be moved from the Spirit Furnace to the Diamond Chest according to the extraction settings.

#### Actual behaviour:
Mob drops remain in the Spirit Furnace. No mob drops land in the Diamond Chest.

#### Steps to reproduce the problem:

Controller
Red Connectors
Red Cables
16x Arboreal Extractors
5x 144B Dark Tanks
1x Blood Infuser (Promise of Tenacity III, 4x Promise of Productivity, 4x Promise of Velocity)
1x Spirit Furnace (Promise of Tenacity II, 4x Promise of Productivity)
1x Entangled Chalice
1x Diamond Chest
Channel 1 (fluid) extracts from the 16 Arboreal Extractors every 100 ticks and inserts into the 5 Dark Tanks.
Channel 2 (fluid) extracts from the 5 Dark Tanks every 100 ticks and inserts into the Blood Infuser, Spirit Furnace, and Entangled Chalice.
Channel 3 (item) extracts from the Spirit Furnace every 100 ticks and inserts into the Diamond Chest.

I'm using a Box of Eternal Closure containing an Enderman, which drops Ender Pearls, Ender Tears, and Nebulous Hearts. None of these are ever extracted from the Spirit Furnace. The rest of the system (the two fluid channels) appears to work just fine.

____
#### Versions:

FTB Horizons III server

Minecraft: 1.12.2
EvilCraft: 1.12.2-0.10.45
EvilCraft-Compat: 1.0.0
CyclopsCore: 1.12.2-0.11.1
Forge: 8.0.99.99 (Forge Mod Loader) and 14.23.1.2601 (Minecraft Forge)
XNet: 1.12-1.6.7
FTBLib: 4.2.5
FTBUtilities: 4.2.4

#### Log file:
No access currently, have asked server admin for relevant logs.

**Comment by rubensworks** [comment] 2018-05-02 18:11
Please update to the latest EC version, you're way behind.

Also, could you check with a plain hopper?

**Comment by rubensworks** [comment] 2018-05-06 09:42
@matthewspeck Any update on this? Closing otherwise.

**Comment by matthewspeck** [comment] 2018-05-06 23:13
@rubensworks I haven't yet had an opportunity to test with a newer build. I suppose I can setup a single-player, local world to test, but am about to leave town for the next several days, and won't have the chance to do so soon. My server owner has setup a new server with updated versions (.55 of EvilCraft, for instance), and I will test when my character has sufficient progression. For now, please feel free to close this issue, as the response provided is reasonable, if not decisive. If the issue persists, I'll post again here and we can talk about reopening.

Thanks for the feedback.

**Comment by rubensworks** [comment] 2018-05-07 06:00
Sounds good, thanks!

**Comment by UncleCrustyMC** [comment] 2018-05-08 18:25
I am seeing a similar issue with the latest version of EnderIO. I cannot
pump out mob drops from the spirit furnace. The item conduit is connected
to the spirit furnace key block. All mods are up to date . Let me know if
you need more info.

**Comment by rubensworks** [comment] 2018-05-09 06:27
@UncleCrustyMC What about hoppers?

> All mods are up to date

Please provide exact mod versions.

**Comment by UncleCrustyMC** [comment] 2018-05-09 15:17
I will try hoppers tonight. In theory, should item extraction work from any
face of the multiblock?

Mod info:
Minecraft 1.12.2
Evilcraft 0.10.56
Cyclops Core 0.11.5
Ender IO 5.0.22
EnderCore 0.5.20

Let me know if you need more info!

Thanks

**Comment by UncleCrustyMC** [comment] 2018-05-09 16:06
Vanilla hopper does not work.

I attached it in the middle/bottom of the multi-block.

**Comment by rubensworks** [comment] 2018-05-10 07:39
> I will try hoppers tonight. In theory, should item extraction work from any
face of the multiblock?

Wait, you are extracting from the core, right? Because only the core will work. Can you share a screenshot?

**Comment by rubensworks** [comment] 2018-05-10 12:06
I tried just about everything, and I can't reproduce the problem at all.

**Comment by UncleCrustyMC** [comment] 2018-05-10 13:22
Ok! My core was in the middle facing , not the bottom where I had the
hopper. I will set the core on a bottom edge tonight and try again. Are you
able to use EnderIO?

**Comment by rubensworks** [comment] 2018-05-10 13:27
No, only tested with hoppers. If it works with hoppers it should also work with EnderIO, otherwise it's an issue on EnderIO's end.

**Comment by UncleCrustyMC** [comment] 2018-05-10 13:42
That makes sense. I will test both. If EnderIO has an issue I will let you
know and i will report it to them.

**Comment by UncleCrustyMC** [comment] 2018-05-10 20:02
I verified your advice. It works when the core is on the edge for input and
output. Thanks!

**Comment by rubensworks** [comment] 2018-05-11 11:55
That's great!

**Closed as completed by rubensworks** 2018-05-11 11:55 UTC
Labels: bug, unreproducible, mc-1.12, more-information-needed
