### ISSUE TITLE
Purifier may not cleanup nbt tags correctly

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/EvilCraft#395] opened 2016-05-19 17:13 UTC
When all enchantments were removed from a purifier, the itemstacks may not be cleaned of nbt data correctly, to be investigated.
It may be the cause of this: Corail31/recycler#1

**Comment by ghost** [comment] 2016-05-19 17:35
The problem is solved and didn't come from you, thanks a lot ;)

**Comment by rubensworks** [comment] 2016-05-19 17:36
@Corail31 Ok, no problem.
I'll leave this issue open anyways, because I'm not certain that I actually do this cleanup. It should not cause any problems, but it's not very nice.

**Comment by MentalMouse** [comment] 2016-05-19 23:33
One thing it could do is raise the price for re-enchanting the item.

**Comment by MentalMouse** [comment] 2016-05-27 15:26
I have now confirmed that the Purifier does not strip the "prior work cost" from the item.  I stripped my diamond chestplate of three enchantments, most of them applied in parts and/or from combined books.  Trying to re-add Protection IV gave a cost of 19 levels.  When I fed it to Corail's Recycler and remade it from the diamonds, the new cost was 4, and I restored all 3 enchantments for 12 or so levels.  ETA:  This is the 1.9 version

**Comment by immortaleeb** [comment] 2016-06-11 05:46
The purifier should not leave any NBT tags on the itemstacks because it uses `EnchantmentHelper.setEnchantments` which removes the any NBT tags.

Concerning the "prior work cost": I do consider this as a bug and it should be fixed in 1a76807cdcaba335023a1c8fde43ed87d1ae2155

**Closed as completed by immortaleeb** 2016-06-11 05:46 UTC
Labels: mc-1.9
