### ISSUE TITLE
Server Crash When using EvilCrafts Bound Blood Orb (BM API Issue)

### ISSUE THREAD

**Issue by ghost** [rubensworks/EvilCraft#425] opened 2016-07-03 14:37 UTC
Issue Description:

Server Crashes When using Evilcraft's Bound Blood Orb to get blood in the bloodmagic altar.

What happens:

Server Crashes When using Evilcraft's Bound Blood Orb to get blood in the bloodmagic altar.

What you expected to happen:

Supposed to fill the altar with blood but does not register it and simply crashes the server

Steps to reproduce:

Right click Bound Blood Orb from Evilcraft
...
Affected Versions (Do not use "latest"):

BloodMagic: BloodMagic-1.9.4-2.0.2-46
EvilCraft: EvilCraft-1.9.4-0.10.2
Minecraft: 1.9.4
Forge: 12.17.0.1987
Pastebin To Server Crash Report http://pastebin.com/rNMpfNCp

**Comment by immortaleeb** [comment] 2016-07-03 14:41
Duplicate of #418 - this has been fixed already but no new version has been released yet.
Wait for a new version of EvilCraft (should be in a couple of days) or downgrade to an older version of BM for now

**Closed as completed by immortaleeb** 2016-07-03 14:41 UTC
