### ISSUE TITLE
[1.10.1] Crash with GregTech

### ISSUE THREAD

**Issue by lilmoefow** [rubensworks/EvilCraft#488] opened 2016-10-05 19:08 UTC
Try to put a pack together on curse,  not really sure whos side its on so im reporting to both parties.  It crashes on start up.

Crashlog: https://gist.github.com/lilmoefow/0e0461bdd53dcb2f71153955b82045f0

FML Latest: https://gist.github.com/lilmoefow/8571efb364c35ce75b0c261557ea056d

Forge 12.18.1.2095
CyclopsCore-1.9.4-0.7.7.jar
EvilCraft-1.10.2-0.10.11.jar
gregtech-5.10.05.jar
industrialcraft-2-2.6.69-ex110.jar

**Comment by rubensworks** [comment] 2016-10-05 19:09
Duplicate of #479, already fixed, to-be released.

**Comment by lilmoefow** [comment] 2016-10-05 19:10
shit, didnt check the closed issues well enough then.  sorry 'bout that, looking forward to a release :)

**Closed as completed by rubensworks** 2016-10-05 19:09 UTC
