### ISSUE TITLE
Dark tank recipe bug

### ISSUE THREAD

**Issue by Tronio** [rubensworks/EvilCraft#307] opened 2015-11-17 03:28 UTC
I have been testing evilcraft because I really like it, and I found a problem with Dark Tanks.
I managed to upgrade the capacity of just one Dark tank, but when I want to upgrade other, putting another tank in the crafting table, the output item isn't the enhanced Dark Tank. It gives me an enhanced Blood Extractor every time.

I hope you could fix this problem, Im using EvliCraft 0.9.1 for minecraft 1.7.10

(It's really hard to get dark gems)

**Comment by rubensworks** [comment] 2015-11-17 07:24
Duplicate of #298
This has been fixed already, but I still have to get around to making a release with this fix.

**Closed as completed by rubensworks** 2015-11-17 07:24 UTC
Labels: duplicate
