### ISSUE TITLE
Cannot place water using Eternal Water Bucket

### ISSUE THREAD

**Issue by belathus** [rubensworks/EvilCraft#895] opened 2021-12-27 23:45 UTC
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crafted an eternal water bucket. I can use it to pick up water, but for some reason, it will not place water.

I wonder if it is related to this issue: https://github.com/yungnickyoung/YUNGs-Better-Portals/issues/44

#### Steps to reproduce the problem:

1. Craft eternal water bucket
2. attempt to place block of water

#### Expected behaviour:

I expect to be able to place water.

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.16.5
- Forge: 36.2.21

#### Log file:
I didn't see anything in the log that'd indicate this problem at the time of use, but I did see this when starting the server; no idea if it is related: https://gist.github.com/belathus/c4dac6f0bed589815370989f630dbe39

Here is the entire log: https://gist.github.com/belathus/eaac0dde8f285d0af0d01ae3a50093e7

**Comment by rubensworks** [comment] 2021-12-27 23:46
Thanks for reporting!

**Comment by rubensworks** [comment] 2021-12-28 06:57
That log seems very related indeed!
It looks like you have a coremod in your pack messing with buckets, and failing to do so.
Can you check if removing that mod solves the problem?

**Comment by belathus** [comment] 2021-12-28 20:16
Sure!

**Comment by belathus** [comment] 2021-12-28 20:38
You know, I have no idea what mod is causing that. What I know so far is that it isn't Enigmatic Legacy or Placebo.

Edit: It isn't Quark either (which modifies buckets to accept the infinity enchantment).

**Comment by rubensworks** [comment] 2022-01-23 13:33
Closing this here in the meantime, as it's being caused by some other mod.

**Closed as completed by rubensworks** 2022-01-23 13:33 UTC
Labels: bug, other mod, mc-1.16
