### ISSUE TITLE
Dupe of Bound Blood Drop

### ISSUE THREAD

**Issue by MrDvD** [rubensworks/EvilCraft#706] opened 2018-06-27 07:38 UTC
**Issue type:**

🐛 Bug

**Short description:** 
In survival mode, when I hold the bound blood drop in my left hand and try to take blood from any device (Shift + Right Mouse Button), then I have bound blood drop in my left and right hand! (This take away the thing that was in my right hand)

**Versions:**
This mod: **0.10.59**
Minecraft: **1.12.2**
Forge: **14.23.4.2705**

**Log file:** https://bit.ly/2tI3snF _(I hope this is the right log file)_

(I don't know how I came up with this, but I found this bug xd)

**Comment by rubensworks** [comment] 2018-07-01 11:48
Just tested this myself, and I'm not able to reproduce this.

@MrDvD Can you reproduce this with just EvilCraft (and dependencies) installed?

**Comment by MrDvD** [comment] 2018-07-01 12:26
Yeah, this bug works even with these mods:

**EvilCraft** [0.10.59]
**BloodMagic** [2.2.12-97]
**CyclopsCore** [0.11.6]
**Guide API** [1.5-60]

But I noticed 1 condition: It **ONLY** works in survival mode

**Comment by rubensworks** [comment] 2018-07-01 14:45
@MrDvD Then I must be doing something different than you.
Could you share a detailed step-by-step guide that explains how to reproduce this problem? (A video would even better if possible)

**Comment by MrDvD** [comment] 2018-07-03 14:41
Video I would could do, but render + uploading video on YouTube is too long. 
So here's step-by-step guide:

1. Go to **SURVIVAL** mode
2. Take _"Bound Blood Drop"_ in your **LEFT** hand
3. Go to any source of blood (for example, blood infuser)
4. Take blood from this source (Shift + Right Mouse Button)

If that doesn't work, try to turn on auto-filling mode in Bound Blood Drop

**Comment by rubensworks** [comment] 2018-07-14 15:08
Ok, I've managed to reproduce it now, will be fixed in the next update.

**Closed as completed** 2018-07-14 15:12 UTC
Labels: bug, unreproducible, mc-1.12
