### ISSUE TITLE
Forestry crash with latest EvilCraft version

### ISSUE THREAD

**Issue by MinityGames** [rubensworks/EvilCraft#651] opened 2018-02-05 16:59 UTC
- :bug: Bug

____
#### Short description:
Launching the game with Forestry + EvilCraft caused the game to crash during start up.

#### Expected behaviour:
The game would launch correctly.

#### Actual behaviour:
The game ends up crashing.

#### Steps to reproduce the problem:

1. Launch the game with the 2 mod versions specified below.

I was able to fix the problem by downgrading my EvilCraft version to 0.10.45 instead of 0.10.46.
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-0.10.46
- CyclopsCore: 1.12.2-0.11.2
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

#### Log file:

https://pastebin.com/jnR11xrR

**Comment by rubensworks** [comment] 2018-02-05 23:14
Please check closed issues before opening new ones, duplicate of #648.

**Closed as completed by rubensworks** 2018-02-05 23:14 UTC
Labels: duplicate

**Comment by Gorgok** [comment] 2018-02-06 01:28
Evilcraft 1.12.2-0.10.46 does not load with works with forestry_1.12.2-5.8.0.241 or forestry_1.12.2-5.8.0.242 as the fix seems to say. 

Evilcraft 1.12.2-0.10.45 will load with forestry_1.12.2-5.8.0.242 however... Not sure if either actually 'works' for the farmer though.

**Comment by rubensworks** [comment] 2018-02-06 01:29
The fix is not part of a release yet.
