### ISSUE TITLE
Broom part crashing when viewed on creative GUI

### ISSUE THREAD

**Issue by rooben777** [rubensworks/EvilCraft#787] opened 2019-09-18 19:52 UTC
As stated in the title, here is the pastebin:

https://paste.dimdev.org/ifuhuqucec.mccrash

I have seen earlier that BWM has something to do with this, it is indeed included in my pack. 

thank you for your time!

**Comment by rubensworks** [comment] 2019-09-19 06:08
Duplicate of #756.

**Closed as completed by rubensworks** 2019-09-19 06:08 UTC
Labels: duplicate
