### ISSUE TITLE
unsure why not working 

### ISSUE THREAD

**Issue by Dawsondude2023** [rubensworks/EvilCraft#970] opened 2023-02-25 15:38 UTC
try play with evil craft and enderio on 1.12.2 get this error don't know how fixed it 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MixinBooter (!mixinbooter-7.0.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 2/25/23 3:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EvilCraft-Compat (evilcraftcompat)
Caused by: java.lang.NoSuchMethodError: crazypants.enderio.base.recipe.Recipe.<init>(Lcrazypants/enderio/base/recipe/IRecipeInput;ILcrazypants/enderio/base/recipe/RecipeBonusType;[Lcrazypants/enderio/base/recipe/RecipeOutput;)V
	at org.cyclops.evilcraftcompat.modcompat.enderio.EnderIORecipeManager.register(EnderIORecipeManager.java:28)
	at org.cyclops.evilcraftcompat.modcompat.enderio.EnderIOModCompat.onInit(EnderIOModCompat.java:21)
	at org.cyclops.cyclopscore.modcompat.ModCompatLoader.onInit(ModCompatLoader.java:61)
	at org.cyclops.cyclopscore.init.ModBase.callInitStepListeners(ModBase.java:229)
	at org.cyclops.cyclopscore.init.ModBase.init(ModBase.java:292)
	at org.cyclops.evilcraftcompat.EvilCraftCompat.init(EvilCraftCompat.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 226803760 bytes (216 MB) / 1367343104 bytes (1304 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 21 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version       | Source                            | Signature                                |
	|:----- |:--------------------------------- |:------------- |:--------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                         | 1.12.2        | minecraft.jar                     | None                                     |
	| LCHI  | mcp                               | 9.42          | minecraft.jar                     | None                                     |
	| LCHI  | FML                               | 8.0.99.99     | forge-1.12.2-14.23.5.2860.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                             | 14.23.5.2860  | forge-1.12.2-14.23.5.2860.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | mixinbooter                       | 7.0           | minecraft.jar                     | None                                     |
	| LCHI  | crafttweaker                      | 4.1.20        | CraftTweaker2-1.12-4.1.20.685.jar | None                                     |
	| LCHI  | ctgui                             | 1.0.0         | CraftTweaker2-1.12-4.1.20.685.jar | None                                     |
	| LCHI  | endertweaker                      | 1.2.3         | EnderTweaker-1.12.2-1.2.3.jar     | None                                     |
	| LCHI  | jei                               | 4.16.1.301    | jei_1.12.2-4.16.1.301.jar         | None                                     |
	| LCHI  | crafttweakerjei                   | 2.0.3         | CraftTweaker2-1.12-4.1.20.685.jar | None                                     |
	| LCHI  | cyclopscore                       | 1.6.7         | CyclopsCore-1.12.2-1.6.7.jar      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHI  | endercore                         | 1.12.2-0.5.76 | EnderCore-1.12.2-0.5.76.jar       | None                                     |
	| LCHI  | enderio                           | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderiointegrationtic             | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderiobase                       | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderioconduits                   | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderioconduitsappliedenergistics | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderioconduitsopencomputers      | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderioconduitsrefinedstorage     | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderiointegrationforestry        | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderiointegrationticlate         | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderioinvpanel                   | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderiomachines                   | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderiopowertools                 | 5.3.70        | EnderIO-1.12.2-5.3.70.jar         | None                                     |
	| LCHI  | enderioendergy                    | 5.3.70        | EnderIO-endergy-1.12.2-5.3.70.jar | None                                     |
	| LCHI  | evilcraft                         | 0.10.78       | EvilCraft-1.12.2-0.10.78.jar      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHE  | evilcraftcompat                   | 1.0.0         | EvilCraft-1.12.2-0.10.78.jar      | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MixinBooter (!mixinbooter-7.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.94' Renderer: 'NVIDIA GeForce GTX 970/PCIe/SSE2'
	Ender IO: No known problems detected.
	Authlib is : /D:/New%20folder/Instances/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Dawsondude2023** [comment] 2023-02-25 15:39
[crash-2023-02-25_15.37.38-client.txt](https://github.com/CyclopsMC/EvilCraft/files/10831581/crash-2023-02-25_15.37.38-client.txt)

**Comment by Dawsondude2023** [comment] 2023-02-25 15:39
sorry if put this wrong place pretty sure this meant to go in bug area

**Comment by rubensworks** [comment] 2023-02-27 07:21
Duplicate of #807

**Closed as not planned by rubensworks** 2023-02-27 07:21 UTC
