### ISSUE TITLE
Corrupting wolrd crash.

### ISSUE THREAD

**Issue by Piratdu52** [rubensworks/EvilCraft#426] opened 2016-07-04 14:51 UTC
Forge log link: http://pastebin.com/0eSfdKa7

Problem: Crashed my world when i have placed a sanguinary climat controller. Now this world crash instantly with an identical crash log.

Expected behaviour: Playing

Steps to reproduce the problem:
Place a sanguinary climat controller.

**Comment by rubensworks** [comment] 2016-07-04 15:46
Duplicate of #417, this has been fixed in the newest EC version, please update to 0.10.3.

**Closed as completed by rubensworks** 2016-07-04 15:46 UTC
Labels: duplicate
