### ISSUE TITLE
[Crash] When looking at Environmental Accumulator from worldGen structure

### ISSUE THREAD

**Issue by drakray** [rubensworks/EvilCraft#473] opened 2016-08-30 02:20 UTC
Forge log link: http://pastebin.com/mM3irFvJ

Problem: CTD when looking at Environmental Accumulator from worldGen structure. The EnvAcc didn't have the Beam over it.

Expected behaviour: Not to crash when looking at it XD

Steps to reproduce the problem: look at an Accumulator that doesn't have the Beam
- Crash
- ???

**Comment by drakray** [comment] 2016-08-30 02:24
Saw the drpmedieval part, posted to [Dark Roleplay Medieval](https://minecraft.curseforge.com/projects/dark-roleplay-medieval/issues/4) too

**Comment by rubensworks** [comment] 2016-08-30 06:14
Duplicate of https://github.com/CyclopsMC/CyclopsCore/issues/23

**Closed as completed by rubensworks** 2016-08-30 06:14 UTC
