### ISSUE TITLE
craft tank into extractor

### ISSUE THREAD

**Issue by ewsmith** [rubensworks/EvilCraft#302] opened 2015-11-08 19:00 UTC
crafting two tanks together gives a blood extractor instead of a tank
note: the extractor had the expected capacity and i wasn't crafting an extractor with them

**Comment by rubensworks** [comment] 2015-11-08 19:09
Duplicate of #298, the fix will be released soon.
Thanks for reporting anyways.

**Closed as completed by rubensworks** 2015-11-08 19:09 UTC
Labels: duplicate
