### ISSUE TITLE
Blood infuser crash

### ISSUE THREAD

**Issue by KawaiiCh4n** [rubensworks/EvilCraft#457] opened 2016-08-10 09:20 UTC
Forge log link: http://pastebin.com/CM0HKqRt

Problem: 
When I try to place ANY item in the blood infuser it crashes, tried it on different worlds
with the latest version of evil craft, I'm using a modified version of Natural Magic,  if that helps

Expected behaviour:
Place an item in the blood infuser and then a freeze, after a few seconds it says "Shutting down internal server" then it crashes

Steps to reproduce the problem:
- Use a blood infuser
- Place an item that you wanna infuse in the working slot

**Comment by KawaiiCh4n** [comment] 2016-08-10 09:22
Also using 1.7.10 :D

**Comment by rubensworks** [comment] 2016-08-10 09:24
Duplicate of #235, which was fixed in Forge a long, long time ago.
You should update your Forge version.
You are currently using 10.13.3.1387, while 10.13.4.1614 is out already.

**Closed as completed by rubensworks** 2016-08-10 09:24 UTC
Labels: duplicate

**Comment by KawaiiCh4n** [comment] 2016-08-10 09:31
I tried with all the new forge versions, and older ones, and recommended ones

**Comment by rubensworks** [comment] 2016-08-10 09:32
You have invalid java libraries that are required by Forge, remove them, and try a clean install of Forge.

**Comment by KawaiiCh4n** [comment] 2016-08-10 09:38
Hmm ok, how do I do that?
