### ISSUE TITLE
Dark tank loses upgrades and contents when broken

### ISSUE THREAD

**Issue by ShaunDreclin** [rubensworks/EvilCraft#584] opened 2017-08-26 16:41 UTC
Title

Evilcraft 1.12-0.10.33

**Comment by kurtu5** [comment] 2017-08-29 02:15
I am using EvilCraft-1.12-0.10.33.jar and its still doing this.

**Comment by rubensworks** [comment] 2017-08-29 06:26
@kurtu5 Are you using the latest CC version?

**Comment by dannydjdk** [comment] 2017-09-07 03:00
I can confirm that this is happening in 1.11.2 with CC 0.10.8 and EvilCraft 0.10.30.
When broken with pick, I always end up with an empty 16,000 mb tank.

**Comment by rubensworks** [comment] 2017-09-07 05:50
I still do 1.11.2 fixes for major bugs (like this), yes. This should have been fixed in 0.10.8 though. Will try to look into this soon.

**Comment by rubensworks** [comment] 2017-09-08 18:17
It looks like I only implemented the fix in the 1.12 version, but forgot to backport it to 1.10/1.11, will do that now.

**Comment by rubensworks** [comment] 2017-09-08 18:24
New 1.10 and 1.11 CyclopsCore versions have been pushed to CurseForge, you'll see them once they have been approved.

**Closed as completed by rubensworks** 2017-09-08 18:24 UTC
Labels: bug, mc-1.10, mc-1.11

**Comment by belathus** [comment] 2017-09-25 00:41
How long does approval usually take? I don't see the update yet on CurseForge.

**Comment by rubensworks** [comment] 2017-09-26 01:01
@belathus The update is there, it was approved on the same day (i.e. 17 days ago), just use the latest version and you should be fine.

**Comment by belathus** [comment] 2017-09-26 13:11
Oh, I see. I need to update Cyclops Core.
